### ISSUE TITLE
Heroku installation

### ISSUE THREAD

**Issue by yu3ver** [cerclecrm/cercle#132]
Hi Antoine,

Tried to use elixir buildpack and received errors ([Push failed.txt](https://github.com/cerclecrm/cercle/files/1273053/Push.failed.txt)).

Maybe there be a manual how to do it properly or how to fix?

Thanks.

**Comment by antoineherzog** [comment]
To Install Cercle into heroku

mix phoenix.gen.secret
heroku config:set SECRET_KEY_BASE="your_key_here"
heroku config:set POOL_SIZE=18
add others parameters from dev.secret into Heroku config:set
You're good to go!
