### ISSUE TITLE
Privacy policy for cercle.co projects

### ISSUE THREAD

**Issue by cedewey** [cerclecrm/cercle#221]
I just learned about Cercle and so far I really like it.

What is your privacy policy and terms of use for projects and accounts on cercle.co? It would be good to post this publicly so that other prospective users can make an informed choice as well.

Thanks and keep up the great work,
Clayton

**Comment by antoineherzog** [comment]
Hi Clayton,

Thank you for your message!

Right now, we maintain cercle.co as a generous way to test to Cercle. We don't do anything with the data.

We are working on a privacy policy.

Thank you for your support!

Kind regards

Antoine
