### ISSUE TITLE
Can't run, getting an error in mix ecto.create. What are the min version requirements?

### ISSUE THREAD

**Issue by Ryanauger95** [cerclecrm/cercle#222]
I'm trying to learn Pheonix for a school project, but I can't get this to compile:

===> Fetching rebar3_hex v6.11.6
===> Version cached at /Users/ryanauger/.cache/rebar3/hex/hexpm/packages/rebar3_hex-6.11.6.tar is up to date, reusing it
escript: exception error: undefined function erlang:get_stacktrace/0
  in function  rebar3:main/1 (/rebar3/src/rebar3.erl, line 72)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
** (Mix) Could not compile dependency :p1_utils, "/Users/ryanauger/.mix/rebar3 bare compile --paths /Users/ryanauger/Repos/cercle/_build/dev/lib/*/ebin" command failed. You can recompile this dependency with "mix deps.compile p1_utils", update it with "mix deps.update p1_utils" or clean it with "mix deps.clean p1_utils"

Is there a minimum version for rebar3/erlang/elixir/pheonix that is required?

**Comment by antoineherzog** [comment]
it is a very old project. Not up to date since a long time!

**Comment by tineo** [comment]
You have to update deps version.

**Comment by Ryanauger95** [comment]
Thanks all, understand now that this is an outdated repo. You can close.

--
Ryan Auger
704-578-1352
