### ISSUE TITLE
Should we manage Notifications in a separate OTP/App?

### ISSUE THREAD

**Issue by agustif** [cerclecrm/cercle#31]
Hi Guys! Thanks @antoineherzog  for adding me to the cercle trello!

I looked up around the trello to see if this was on the backlog. 

I saw the task :https://trello.com/c/ltFmQZ1B/50-add-reminders-for-task

It make me think, maybe we would better leverage a way to -dispatch- notifications, and have it manage web-ui, email, desktop, and other channels which may become useful as hooks.

I know the guys at actuario have build this in elixir [ravenx](https://github.com/acutario/ravenx) which looks very useful for scaling on more integrations down the road.

I'm not sure how harder it would be to implement an external dependency vs integrating just what we need, but I wanted to note the existence of this.

Also this, which seems to be more about @ mentions than notifications.
https://trello.com/c/udG6Nfr3/5-6-build-notification-system-like-trello-with-vuejs

**Comment by antoineherzog** [comment]
@agustif yeah dispatch notifications it is going to be important. I checked the library ravenx and I think we should be able to send notifications into Zapier so Cercle can used by different tool. But i don't see a Zapier strategy :-\ not sure if we should add one or maybe look for another library.

In the short term, we need to fix a couple of small bugs so we can release version 1.0 

Lets meet in Barcelona in 2 week.s Maybe before we can do a quick chat on skype : azekl1979

See you!

**Comment by agustif** [comment]
Great, seeing the Bamboo/Slack Examples on ravenx seems straightforward enought to try to make a PR to.

**Comment by antoineherzog** [comment]
@agustif for now i close the issue because we are focus to release version 1.0 very soon ;)
