### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by agustif** [cerclecrm/cercle#34]
I see we're using guardian, but I've read some bad rap, and that we need stuff like [guardian_db](https://github.com/ueberauth/guardian_db) in order to be able to delete sessions.

I, for example, plan to use this with remote workers, which may leave the company at some point and I would need a way to be able to terminate all its sessions.

Also, there's doubt about how storing JWT is exactly better than cookies and such...

Anyways, I also saw a trello card about invitations not working. 

Maybe we could leverage the use of [Coherence](https://github.com/smpallen99/coherence), which if it's not exactly stated in the readme does allow its use with API endpoints only.

It also covers a lot of -features that usually are a nice to have, if not lifesavers, like invitable, recoverable, confirmable, and some more!!

**Comment by antoineherzog** [comment]
So far, guardian is good, so we keep it. Invitation link has been fixed. They are working now!
Regarding token issue, we can do that later ;) After version 1.0
Kind regards,
Antoine
