### ISSUE TITLE
Adding contact error/enhancement

### ISSUE THREAD

**Issue by jfayad** [cerclecrm/cercle#69]
If I try to add a contact with a random phone number the page freezes, when checking the console log I can see a JS error:

`Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)`

The values I'm trying with are:
Name: Hey
Email: Hey
Phone: 122233

If I try to use the same values but with a more "legit" phone number (i.e 01223334) then it succeeds.

I suggest the following:

- [ ] Provide clear error messages on what is wrong (duplicate field X, wrong format of field X, etc...)
- [ ] Validate email formats

**Comment by antoineherzog** [comment]
@jfayad Hi Julien!
Thank you very much for your valuable feedback. We are working on this issue right now. It should be fix today. Our software is still in alpha version. Kind regards Antoine

**Comment by antoineherzog** [comment]
@jfayad this is fixed. We don't validate any field so far. We can add any information you want.

https://github.com/cerclecrm/cercle/commit/fb1abd1aaa70c51af594c03b5548a60cbea48b71

**Comment by jfayad** [comment]
hey @antoineherzog thanks for the quick reply, is it deployed on the test URL you provided ?

I've seen you are willing to release a 1.0 soon, I'll try to keep on testing and submitting feedbacks to get this polished up.

**Comment by antoineherzog** [comment]
@jfayad yes deployed ;)

Sounds good!
