### ISSUE TITLE
UX enhancements

### ISSUE THREAD

**Issue by jfayad** [cerclecrm/cercle#70]
After a contact has been added, the screen showing the details of a contact is not extremely clear. Some fields (i.e adding a task shows a select list with TE inside it ?) are not very clear, the UX is not polished up (adding a task pops up the "add a contact" box ?)
Marking a task as done (by ticking the checkbox next to it) should cross the task and not make it disappear... we want to keep a history of tasks done.

I'm also wondering if putting tasks on a contact level is the best approach but that's another topic...

Finally it's not very clear if we'll get a reminder on tasks that are being inputted and how will the reminder show (if any), will it be on the app itself ? will it be an email ?

**Comment by antoineherzog** [comment]
@jfayad we use Zapier for notification. We have a full API working very well. So you can have notifications for a bunch of different events.

We are going to display marked tasks with a toggle button (hide/show marked tasks)

The tasks are grouped by card. Each card can have many contacts (usefull when you do Sales Deals)

The add a contact display bug has been fixed today (https://github.com/cerclecrm/cercle/commit/2d17105e14d5507182eebcc200d3eaf5aca9bd2e)

Kind regards,

Antoine

**Comment by jfayad** [comment]
Zapier seems cool but I don't know it, any idea about their data retention rule ? Like if a company wants to keep its data private, how reliable would Zapier be ?

If Zapier isn't the best candidate for privacy, how "easy" (i.e without coding in cercle) is it to plug another system ?

**Comment by antoineherzog** [comment]
@jfayad Zapier doens't save any data . Zapier just pass informaiton from one trigger to one action. Very usefull to do automation technique ;) We are planning to have a better integration with Zapier next week.

**Comment by antoineherzog** [comment]
Marking a task as done (by ticking the checkbox next to it) should cross the task and not make it disappear... we want to keep a history of tasks done.
https://github.com/cerclecrm/cercle/pull/86
@jfayad it has been fixed today
