### ISSUE TITLE
Websocket connection error on the Contact Page

### ISSUE THREAD

**Issue by jfayad** [cerclecrm/cercle#73]
After I added a contact I land on the contact details page, here clicking on Add a task doesn't work, the console shows the following error:

`WebSocket connection to 'ws://www.cercle.co/socket/websocket?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.e…QVrRZeBiHtnwg6OTjQgeJ8mXjVwZXb80jQh2u4xVHGR0tSSHxB6jSt01TB2_Zx3Q&vsn=1.0.0' failed: Error during WebSocket handshake: Unexpected response code: 400`

**Comment by antoineherzog** [comment]
@jfayad @parallel588 Maxim is working on it ;)

**Comment by antoineherzog** [comment]
@jfayad @parallel588  it has been fixed.
