### ISSUE TITLE
Not clear how to use some advertised features

### ISSUE THREAD

**Issue by jfayad** [cerclecrm/cercle#87]
The following features are not clear on how they can be used:

- [ ] Real time chat in between sales people
- [ ] Support ticket management
- [ ] Integration with other tools through the API Key

**Comment by jfayad** [comment]
are these ready or they are simply not part of this version @antoineherzog ?

**Comment by jfayad** [comment]
Any updates here ?

**Comment by antoineherzog** [comment]
@jfayad Lets do a skype ? so we can chat a little bit?
