### ISSUE TITLE
Errors showing make the registration page unusable

### ISSUE THREAD

**Issue by jfayad** [cerclecrm/cercle#88]
If you trigger an error (password too short) on the registration page then the action button won't show anymore and no scroll is possible.

<img width="440" alt="screen shot 2017-06-10 at 00 31 44" src="https://user-images.githubusercontent.com/6277804/26995287-69b12e98-4d74-11e7-927f-9b0d70ef7e71.png">

**Comment by antoineherzog** [comment]
@jfayad it is fixed.
https://github.com/cerclecrm/cercle/commit/af554fb013a85e35342c2d55383e0ed21aa3fbd2
