### ISSUE TITLE
Importing a file (xslx) fails

### ISSUE THREAD

**Issue by jfayad** [cerclecrm/cercle#89]
Dropping the file in the upload area recognizes the file and its type. Then clicking next shows the upload progress, yet it never finishes.

Checking the console shows the following:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)  on import_data

On top of it, the http://www.cercle.co/import_data returns a "Page not found" but not a regular error page.

**Comment by jfayad** [comment]
actually, it seems that this occurs with xlsx file types. A csv succeeded to the next step

**Comment by antoineherzog** [comment]
@jfayad thank you for the bug report, we will display a nice error message for xslx !

**Comment by antoineherzog** [comment]
@harish86 Could you take care of that?

**Comment by harish86** [comment]
@antoineherzog Sure, I will take care of it

**Comment by antoineherzog** [comment]
@parallel588 Could you fix the issue during the refactoring?

**Comment by parallel588** [comment]
yes, I'll look it

**Comment by jfayad** [comment]
no update over here @parallel588 @antoineherzog

**Comment by antoineherzog** [comment]
@parallel588 is it fixed?

**Comment by antoineherzog** [comment]
@jfayad it should be fixed very soon.

**Comment by parallel588** [comment]
yes, it's ready and deployed now.

**Comment by antoineherzog** [comment]
great
