### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by brainlid** [cerclecrm/cercle#95]
I identified multiple security vulnerabilities in your project. I was writing a blog post showing how to use [sobelow](https://github.com/nccgroup/sobelow) for performing security scans on Phoenix applications and I randomly selected your project for testing it on.

I don't directly identify your project in my article. However, I wanted to reach out and make you aware of the issues so you can correct them. Running `sobelow` is really easy. Here's a link to my [article](https://brainlid.org/elixir/2017/06/14/security-scanning-phoenix.html) as well.

The most severe problems and potentially fastest fixes are updating the version of Phoenix you are using as it has known vulnerabilities.

**Comment by antoineherzog** [comment]
@brainlid Dear Mark
Thank you for your ticket.
@parallel588 Maxim could you fix?
Kind regards,
Antoine

**Comment by parallel588** [comment]
yes, I'll do it

**Comment by parallel588** [comment]
ready

**Comment by antoineherzog** [comment]
@parallel588 did you run sobelow?
Are we good now?
