### ISSUE TITLE
When adding a contact to a board the UX is confusing

### ISSUE THREAD

**Issue by jfayad** [cerclecrm/cercle#97]
- Click on a contact
- Click on "add to a board"
- Select a board with steps
- You'll see multiple boxes (as much as you have steps in the board I guess) but they are all named after the board name (this is the first confusing issue to fix)
- Then you don't know what you have to do and it seems you have to select to which step to add the contact (this is the second confusion as this should be clearer)
- Finally, once you are done, you receive no confirmation on screen and you don't know if it's been done correctly

**Comment by antoineherzog** [comment]
@jfayad i don't understand the issue. Let's chat!
